version: '3'

services:
  db:
    image: postgres:9
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
     - "5432:5432"
  web:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    environment:
      DEBUG: '1'
    command: bash bootstrap-dev.sh
    volumes:
      - ./backend:/var/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
    driver: local
