version: '3'

services:
  db:
    image: postgres:9
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
  web:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_PORT=5432
      - ALLOWED_HOSTS=platform.allhere.co,.eksdev.nonprod.allhere.co,localhost
    command: bash bootstrap-dev.sh
    volumes:
      - ./backend:/var/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
    driver: local
