apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "allhere.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "allhere.name" . }}
    helm.sh/chart: {{ include "allhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "allhere.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "allhere.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: allhereapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - bash
{{- if eq .Values.configMap.debug "0" }}
          - bootstrap-prod.sh
{{- else }}
          - bootstrap-dev.sh
{{- end }}
          envFrom:
          - configMapRef:
              name: {{ include "allhere.fullname" . }}
          - secretRef:
              name: {{ include "allhere.fullname" . }}          
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
              - name: Host
                value: "127.0.0.1"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
              - name: Host
                value: "127.0.0.1"
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- if .Values.reviewApp }}
        - name: db
          image: postgres:9
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 5432
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
