{{- if .Values.reviewApp }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: {{ include "allhere.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "allhere.name" . }}
    helm.sh/chart: {{ include "allhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Release.Name }}.eksdev.nonprod.allhere.co
    http:
      paths:
      - backend:
          serviceName: {{ include "allhere.fullname" . }}
          servicePort: 8000
        path: /
{{- end }}
