apiVersion: v1
kind: Secret
metadata:
  name: {{ include "allhere.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "allhere.name" . }}
    helm.sh/chart: {{ include "allhere.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- with .Values.secret }}
  DB_USER: {{ default "" .dbUser | b64enc | quote }}
  DB_PASSWORD: {{ default "" .dbPassword | b64enc | quote }}
  DJANGO_SECRET_KEY: {{ default "" .djangoSecretKey | b64enc | quote }}
  EDNUDGE_USERNAME: {{ default "" .ednudgeUsername | b64enc | quote }}
  EDNUDGE_PASSWORD: {{ default "" .ednudgePassword | b64enc | quote }}
{{- end }}
